import { useTranslation } from 'react-i18next'

const useGetMenuCardsItems = () => {
  const { t } = useTranslation()

  return [
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/66e1df470dca4046bab46a195f10f941/d353a15072aeb4ca0635df1ef66e0a4c.webp',
      title: t('menuCardsItems.carneGherghievschi'),
      description: t('menuCardsItems.descCarne'),
      group: 'main_dish',
      weight: 400,
      price: 353,
    },
    {
      title: t('menuCardsItems.friptura'),
      description: t('menuCardsItems.descFriptura'),
      group: 'lamb',
      weight: 400,
      price: 194,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/d2980b6a04614a6a84169d2b13eb7135/eccc922e4099e0ff48246f0f576d5f30.webp',
      title: t('menuCardsItems.budjak'),
      description: t('menuCardsItems.descBudjak'),
      group: 'main_dish',
      weight: 400,
      price: 249,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/c11700a5618a421ea2bf00cba9e05fac/a83556daba0568b860e12f5917f68d71.webp',
      title: t('menuCardsItems.borsRosu'),
      description: t('menuCardsItems.descBorsRosu'),
      group: 'supe',
      weight: 350,
      price: 93,
    },
    {
      title: t('menuCardsItems.musafiri'),
      description: t('menuCardsItems.descMusafiri'),
      group: 'main_dish',
      weight: 325,
      price: 179,
    },
    {
      title: t('menuCardsItems.ardeiUmplut'),
      description: t('menuCardsItems.descArdeiUmplut'),
      group: 'main_dish',
      weight: 150,
      price: 107,
    },
    {
      title: t('menuCardsItems.ardeiDulce'),
      description: t('menuCardsItems.descArdeiDulce'),
      group: 'main_dish',
      weight: 250,
      price: 97,
    },
    {
      title: t('menuCardsItems.ardeiDulce'),
      description: t('menuCardsItems.descArdeiDulce'),
      group: 'main_dish',
      weight: 250,
      price: 97,
    },
    {
      title: t('menuCardsItems.laRachiu'),
      description: t('menuCardsItems.descLaRachiu'),
      group: 'main_dish',
      weight: 360,
      price: 151,
    },
    {
      title: t('menuCardsItems.dinSomon'),
      description: t('menuCardsItems.descDinSomon'),
      group: 'main_dish',
      weight: 130,
      price: 179,
    },
    {
      title: t('menuCardsItems.heringCeapa'),
      description: t('menuCardsItems.descHeringCeapa'),
      group: 'main_dish',
      weight: 310,
      price: 107,
    },
    {
      title: t('menuCardsItems.cartofiHering'),
      description: t('menuCardsItems.descCartofiHering'),
      group: 'main_dish',
      weight: 430,
      price: 123,
    },
    {
      title: t('menuCardsItems.salataBulgara'),
      description: t('menuCardsItems.descSalataBulgara'),
      group: 'salads',
      weight: 300,
      price: 93,
    },
    {
      title: t('menuCardsItems.salataIliderim'),
      description: t('menuCardsItems.descSalataIliderim'),
      group: 'salads',
      weight: 350,
      price: 97,
    },
    {
      title: t('menuCardsItems.salataDeSarbatoare'),
      description: t('menuCardsItems.descSalataDeSarbatoare'),
      group: 'salads',
      weight: 300,
      price: 163,
    },
    {
      title: t('menuCardsItems.salataPlacereaSef'),
      description: t('menuCardsItems.descPlacereaSef'),
      group: 'salads',
      weight: 300,
      price: 97,
    },
    {
      title: t('menuCardsItems.salataFierbinte'),
      description: t('menuCardsItems.descSalataFierbinte'),
      group: 'salads',
      weight: 300,
      price: 137,
    },
    {
      title: t('menuCardsItems.salataContemporan'),
      description: t('menuCardsItems.descSalataContemporan'),
      group: 'salads',
      weight: 220,
      price: 121,
    },
    {
      title: t('menuCardsItems.salataDeLegume'),
      description: t('menuCardsItems.descSalataDeLegume'),
      group: 'salads',
      weight: 220,
      price: 89,
    },
    {
      title: t('menuCardsItems.salataSmantana'),
      description: t('menuCardsItems.descSalataSmantana'),
      group: 'salads',
      weight: 220,
      price: 89,
    },
    {
      title: t('menuCardsItems.salataIarna'),
      description: t('menuCardsItems.descSalataIarna'),
      group: 'salads',
      weight: 220,
      price: 77,
    },
    {
      title: t('menuCardsItems.ciorbaComrat'),
      description: t('menuCardsItems.descCiorbaComrat'),
      group: 'supe',
      weight: 355,
      price: 93,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/ab1746efaae644e9ad2473e66f549527/7a3eb33ed28af5b0e63cf0b386c8cbc1.webp',
      title: t('menuCardsItems.ciorbaGaina'),
      description: t('menuCardsItems.descCiorbaGaina'),
      group: 'supe',
      weight: 350,
      price: 93,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/67c02533eace46eeb418f36e83b49a4d/62b004ced266045155b56210a6c605c3.webp',
      title: t('menuCardsItems.borsVerde'),
      description: t('menuCardsItems.descBorsVerde'),
      group: 'supe',
      weight: 350,
      price: 132,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/9935033bb8bd48beaa80eaf0e454dc7f/be032167fd99aa211c0e6b422a7c0ba3.webp',
      title: t('menuCardsItems.supaHarcio'),
      description: t('menuCardsItems.descSupaHarcio'),
      group: 'supe',
      weight: 330,
      price: 146,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/e0c34390a5534503ad049b8c341eda34/503249f93c5b02285d7e09e857869102.webp',
      title: t('menuCardsItems.bulionMiel'),
      description: t('menuCardsItems.descBulionMiel'),
      group: 'supe',
      weight: 300,
      price: 137,
    },
    {
      title: t('menuCardsItems.tarator'),
      description: t('menuCardsItems.descTarator'),
      group: 'supe',
      weight: 300,
      price: 129,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/38eab48a046e47358bc6d695ae9db3db/c80247de0f084059a05c7ed539c8f08b.webp',
      title: t('menuCardsItems.surpa'),
      description: t('menuCardsItems.descSurpa'),
      group: 'supe',
      weight: 520,
      price: 279,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/d3e53a531c6e403fa685c3d900f10836/ed1bd5914818995399b788db1b611f18.webp',
      title: t('menuCardsItems.lagman'),
      description: t('menuCardsItems.descLagman'),
      group: 'supe',
      weight: 450,
      price: 238,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/17520491e0844346ac11a35b3fce0747/0271ab00f06db09f4bac68b614c39c1f.webp',
      title: t('menuCardsItems.pieptMiel'),
      description: t('menuCardsItems.descPieptMiel'),
      group: 'lamb',
      weight: 440,
      price: 194,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/2a6bf28e668d402abc1a6f38a6d68027/571a19da5bdff3451f63f51bab02031d.webp',
      title: t('menuCardsItems.kebabMiel'),
      description: t('menuCardsItems.descKebabMiel'),
      group: 'lamb',
      weight: 350,
      price: 237,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/0d5124e6973d46f091e583531d14da1b/f884be962da1dd272fae818860136337.webp',
      title: t('menuCardsItems.ghiveciMiel'),
      description: t('menuCardsItems.descGhiveciMiel'),
      group: 'lamb',
      weight: 350,
      price: 204,
    },
    {
      title: t('menuCardsItems.fripturaBulgareasca'),
      description: t('menuCardsItems.descFripturaBulgareasca'),
      group: 'lamb',
      weight: 300,
      price: 159,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/3761855ffb414726875a348cf2749379/eb1c83cc9fa290732a1af88414298a7c.webp',
      title: t('menuCardsItems.pirinci'),
      description: t('menuCardsItems.descPirinci'),
      group: 'lamb',
      weight: 400,
      price: 194,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/a4f7cfe139164463a3a1c29832140801/da4281e2e1a236a5c76a8202db14f057.webp',
      title: t('menuCardsItems.fasoleMiel'),
      description: t('menuCardsItems.descFasoleMiel'),
      group: 'lamb',
      weight: 400,
      price: 194,
    },
    {
      title: t('menuCardsItems.oiteSos'),
      description: t('menuCardsItems.descOiteSos'),
      group: 'lamb',
      weight: 500,
      price: 167,
    },
    {
      title: t('menuCardsItems.mielInabusit'),
      description: t('menuCardsItems.descMielInabusit'),
      group: 'lamb',
      weight: 100,
      price: 123,
    },
    {
      title: t('menuCardsItems.manti'),
      description: t('menuCardsItems.descManti'),
      group: 'lamb',
      weight: 550,
      price: 327,
    },
    {
      title: t('menuCardsItems.suvanniPork'),
      description: t('menuCardsItems.descSuvanniPork'),
      group: 'pork',
      weight: 300,
      price: 167,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/b91acd91a22e4ce3bfc6e9ebccce8fd2/77d37723b05b1e31351374a6afb2fbd3.webp',
      title: t('menuCardsItems.steakPork'),
      description: t('menuCardsItems.descSteakPork'),
      group: 'pork',
      weight: 380,
      price: 238,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/39e8d692ebaf4ecbbad297e2d2fce267/9d968a8d07b45052bf2a4d186af75577.webp',
      title: t('menuCardsItems.frigaruiPork'),
      description: t('menuCardsItems.descFrigaruiPork'),
      group: 'pork',
      weight: 390,
      price: 229,
    },
    {
      title: t('menuCardsItems.mangiaGaina'),
      description: t('menuCardsItems.descMangiaGaina'),
      group: 'chicken',
      weight: 370,
      price: 139,
    },
    {
      title: t('menuCardsItems.mangiaGainaSmantana'),
      description: t('menuCardsItems.descMangiaGainaSmantana'),
      group: 'chicken',
      weight: 370,
      price: 139,
    },
    {
      title: t('menuCardsItems.fileuGaina'),
      description: t('menuCardsItems.descFileuGaina'),
      group: 'chicken',
      weight: 220,
      price: 157,
    },
    {
      title: t('menuCardsItems.cavurmaGaina'),
      description: t('menuCardsItems.descCavurmaGaina'),
      group: 'chicken',
      weight: 310,
      price: 147,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/889c8784a66242a69d18afaf09f7cd5f/5ef19d73cd19cbf039872d3fc4d68101.webp',
      title: t('menuCardsItems.piriniciGaina'),
      description: t('menuCardsItems.descPiriniciGaina'),
      group: 'chicken',
      weight: 410,
      price: 139,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/42b3246f5b40457582d1282752e380cc/10cd33ff8c63bb3aee72e66044e05c1b.webp',
      title: t('menuCardsItems.fasoleGaina'),
      description: t('menuCardsItems.descFasoleGaina'),
      group: 'chicken',
      weight: 400,
      price: 171,
    },
    {
      title: t('menuCardsItems.somonGratar'),
      description: t('menuCardsItems.descSomonGratar'),
      group: 'fish',
      weight: 100,
      price: 157,
    },
    {
      title: t('menuCardsItems.cavurmaSomon'),
      description: t('menuCardsItems.descCavurmaSomon'),
      group: 'fish',
      weight: 300,
      price: 167,
    },
    {
      title: t('menuCardsItems.crapPrajit'),
      description: t('menuCardsItems.descCrapPrajit'),
      group: 'fish',
      weight: 100,
      price: 87,
    },
    {
      title: t('menuCardsItems.salauPrajit'),
      description: t('menuCardsItems.descSalauPrajit'),
      group: 'fish',
      weight: 100,
      price: 97,
    },
    {
      title: t('menuCardsItems.salauLegume'),
      description: t('menuCardsItems.descSalauLegume'),
      group: 'fish',
      weight: 500,
      price: 197,
    },
    {
      title: t('menuCardsItems.frigaruiMielOs'),
      description: t('menuCardsItems.descFrigaruiMielOs'),
      group: 'grilled_food',
      weight: 440,
      price: 247,
    },
    {
      title: t('menuCardsItems.fileuVitelGratar'),
      description: t('menuCardsItems.descFileuVitelGratar'),
      group: 'grilled_food',
      weight: 340,
      price: 325,
    },
    {
      title: t('menuCardsItems.frigaruiPorkGarnitura'),
      description: t('menuCardsItems.descFrigaruiPorkGarnitura'),
      group: 'grilled_food',
      weight: 390,
      price: 189,
    },
    {
      title: t('menuCardsItems.steakPorkGarnitura'),
      description: t('menuCardsItems.descSteakPorkGarnitura'),
      group: 'grilled_food',
      weight: 390,
      price: 197,
    },
    {
      title: t('menuCardsItems.fileGainaGratar'),
      description: t('menuCardsItems.descFileGainaGratar'),
      group: 'grilled_food',
      weight: 220,
      price: 137,
    },
    {
      title: t('menuCardsItems.somonGratarGrill'),
      description: t('menuCardsItems.descSomonGratarGrill'),
      group: 'grilled_food',
      weight: 100,
      price: 157,
    },
    {
      title: t('menuCardsItems.kebabGratar'),
      description: t('menuCardsItems.descKebabGratar'),
      group: 'grilled_food',
      weight: 340,
      price: 179,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/163380add9ef4f8f8a2b8ff8f0fd4e2f/42d292dc6eec9aa827fab3a5ba09f395.webp',
      title: t('menuCardsItems.cavurmaMielMamaliga'),
      description: t('menuCardsItems.descCavurmaMielMamaliga'),
      group: 'mamaliga',
      weight: 500,
      price: 342,
    },
    {
      title: t('menuCardsItems.cavurmaSomonMamaliga'),
      description: t('menuCardsItems.descCavurmaSomonMamaliga'),
      group: 'mamaliga',
      weight: 560,
      price: 237,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/f5a06397717d425da8a427482d2742fc/5330835a641c84538247833e17defef1.webp',
      title: t('menuCardsItems.suvanniPorkMamaliga'),
      description: t('menuCardsItems.descSuvanniPorkMamaliga'),
      group: 'mamaliga',
      weight: 560,
      price: 284,
    },
    {
      title: t('menuCardsItems.mangiaGainaRosuMamaliga'),
      description: t('menuCardsItems.descmangiaGainaRosuMamaliga'),
      group: 'mamaliga',
      weight: 610,
      price: 218,
    },
    {
      title: t('menuCardsItems.mangiaGainaSmantanaMamaliga'),
      description: t('menuCardsItems.descmangiaGainaSmantanaMamaliga'),
      group: 'mamaliga',
      weight: 530,
      price: 218,
    },
    {
      title: t('menuCardsItems.mangiaGainaCiuperciMamaliga'),
      description: t('menuCardsItems.descMangiaGainaCiuperciMamaliga'),
      group: 'mamaliga',
      weight: 480,
      price: 218,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/570b5f25f3954be79e20fc023a8fc9ec/927a90842f34e6ada4645102067d75ee.webp',
      title: t('menuCardsItems.cavurmaGainaMamaliga'),
      description: t('menuCardsItems.descCavurmaGainaMamaliga'),
      group: 'mamaliga',
      weight: 470,
      price: 262,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/a8e68509f9e34fd381d8070e2b7aa3eb/96e39763f14900ac5719e9ec719a8c78.webp',
      title: t('menuCardsItems.mamaligaBranzaSmantana'),
      description: t('menuCardsItems.descMamaligaBranzaSmantana'),
      group: 'garnishes',
      weight: 300,
      price: 107,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/c8fd7eb89c7f431b86e1521103e29d6e/3d527e854ac126c749d483a03373d36d.webp',
      title: t('menuCardsItems.orezCascaval'),
      description: t('menuCardsItems.descOrezCascaval'),
      group: 'garnishes',
      weight: 180,
      price: 84,
    },
    {
      title: t('menuCardsItems.cartofiCopti'),
      description: t('menuCardsItems.descCartofiCopti'),
      group: 'garnishes',
      weight: 300,
      price: 119,
    },
    {
      title: t('menuCardsItems.cartofiPrajiti'),
      description: t('menuCardsItems.descCartofiPrajiti'),
      group: 'garnishes',
      weight: 300,
      price: 119,
    },
    {
      title: t('menuCardsItems.cartofiPrajitiBranza'),
      description: t('menuCardsItems.descCartofiPrajitiBranza'),
      group: 'garnishes',
      weight: 300,
      price: 119,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/e37aa142813842d7a40fee4c085c0883/e60449eff8c5be9be6ef378a795e4005.webp',
      title: t('menuCardsItems.taiteiBranza'),
      description: t('menuCardsItems.descTaiteiBranza'),
      group: 'garnishes',
      weight: 250,
      price: 148,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/fef6e61bff0044db8d42f26fc6e86888/dbcd5b36c3d4bdca29a11dd098a544f9.webp',
      title: t('menuCardsItems.legumeCoapte'),
      description: t('menuCardsItems.descLegumeCoapte'),
      group: 'garnishes',
      weight: 100,
      price: 46,
    },
    {
      title: t('menuCardsItems.muraturi'),
      description: t('menuCardsItems.descMuraturi'),
      group: 'garnishes',
      weight: 100,
      price: 30,
    },
    {
      title: t('menuCardsItems.mujdei'),
      description: t('menuCardsItems.descMujdei'),
      group: 'diverse',
      weight: 50,
      price: 21,
    },
    {
      title: t('menuCardsItems.maioneza'),
      description: t('menuCardsItems.descMaioneza'),
      group: 'diverse',
      weight: 50,
      price: 16,
    },
    {
      title: t('menuCardsItems.ketchup'),
      description: t('menuCardsItems.descKetchup'),
      group: 'diverse',
      weight: 50,
      price: 16,
    },
    {
      title: t('menuCardsItems.smantana'),
      description: t('menuCardsItems.descSmantana'),
      group: 'diverse',
      weight: 100,
      price: 22,
    },
    {
      title: t('menuCardsItems.sosVinMiere'),
      description: t('menuCardsItems.descSosVinMiere'),
      group: 'diverse',
      weight: 50,
      price: 53,
    },
    {
      title: t('menuCardsItems.adjicaCasa'),
      description: t('menuCardsItems.descAdjicaCasa'),
      group: 'diverse',
      weight: 50,
      price: 35,
    },
    {
      title: t('menuCardsItems.cavurmaRece'),
      description: t('menuCardsItems.descCavurmaRece'),
      group: 'diverse',
      weight: 100,
      price: 87,
    },
    {
      title: t('menuCardsItems.basturma'),
      description: t('menuCardsItems.descBasturma'),
      group: 'diverse',
      weight: 50,
      price: 85,
    },
    {
      title: t('menuCardsItems.slanina'),
      description: t('menuCardsItems.descSlanina'),
      group: 'diverse',
      weight: 100,
      price: 67,
    },
    {
      title: t('menuCardsItems.carneSlaninaPorc'),
      description: t('menuCardsItems.descCarneSlaninaPorc'),
      group: 'diverse',
      weight: 100,
      price: 67,
    },
    {
      title: t('menuCardsItems.branza'),
      description: t('menuCardsItems.descBranza'),
      group: 'diverse',
      weight: 100,
      price: 43,
    },
    {
      title: t('menuCardsItems.cascaval'),
      description: t('menuCardsItems.descCascaval'),
      group: 'diverse',
      weight: 100,
      price: 43,
    },
    {
      title: t('menuCardsItems.masline'),
      description: t('menuCardsItems.descMasline'),
      group: 'diverse',
      weight: 100,
      price: 34,
    },
    {
      title: t('menuCardsItems.olive'),
      description: t('menuCardsItems.descOlive'),
      group: 'diverse',
      weight: 100,
      price: 34,
    },
    {
      title: t('menuCardsItems.unt'),
      description: t('menuCardsItems.descUnt'),
      group: 'diverse',
      weight: 50,
      price: 22,
    },
    {
      title: t('menuCardsItems.uleiMasline'),
      description: t('menuCardsItems.descUleiMasline'),
      group: 'diverse',
      weight: 50,
      price: 27,
    },
    {
      title: t('menuCardsItems.castravetiRosii'),
      description: t('menuCardsItems.descCastravetiRosii'),
      group: 'diverse',
      weight: 100,
      price: 32,
    },
    {
      title: t('menuCardsItems.ardeiGras'),
      description: t('menuCardsItems.descArdeiGras'),
      group: 'diverse',
      weight: 100,
      price: 32,
    },
    {
      title: t('menuCardsItems.ciuperciMarinate'),
      description: t('menuCardsItems.descCiuperciMarinate'),
      group: 'diverse',
      weight: 100,
      price: 34,
    },
    {
      title: t('menuCardsItems.ciuperciPrajite'),
      description: t('menuCardsItems.descCiuperciPrajite'),
      group: 'diverse',
      weight: 100,
      price: 34,
    },
    {
      title: t('menuCardsItems.ceapaMarinata'),
      description: t('menuCardsItems.descCeapaMarinata'),
      group: 'diverse',
      weight: 50,
      price: 10,
    },
    {
      title: t('menuCardsItems.usturoi'),
      description: t('menuCardsItems.descUsturoi'),
      group: 'diverse',
      weight: 25,
      price: 10,
    },
    {
      title: t('menuCardsItems.nuci'),
      description: t('menuCardsItems.descNuci'),
      group: 'diverse',
      weight: 50,
      price: 32,
    },
    {
      title: t('menuCardsItems.verdeata'),
      description: t('menuCardsItems.descVerdeata'),
      group: 'diverse',
      weight: 100,
      price: 35,
    },
    {
      title: t('menuCardsItems.kefir'),
      description: t('menuCardsItems.descKefir'),
      group: 'diverse',
      weight: 330,
      price: 21,
    },
    {
      title: t('menuCardsItems.saramuraVarza'),
      description: t('menuCardsItems.descSaramuraVarza'),
      group: 'diverse',
      weight: 330,
      price: 21,
    },
    {
      title: t('menuCardsItems.lamaie'),
      description: t('menuCardsItems.descLamaie'),
      group: 'diverse',
      weight: 100,
      price: 17,
    },
    {
      title: t('menuCardsItems.ardeiIute'),
      description: t('menuCardsItems.descArdeiIute'),
      group: 'diverse',
      weight: 1,
      price: 4,
    },
    {
      title: t('menuCardsItems.lavash'),
      description: t('menuCardsItems.descLavash'),
      group: 'bread',
      weight: 100,
      price: 10,
    },
    {
      title: t('menuCardsItems.gozlemeCarneBranza'),
      description: t('menuCardsItems.descGozlemeCarneBranza'),
      group: 'bread',
      weight: 110,
      price: 77,
    },
    {
      title: t('menuCardsItems.gozlemeLegume'),
      description: t('menuCardsItems.descGozlemeLegume'),
      group: 'bread',
      weight: 110,
      price: 66,
    },
    {
      title: t('menuCardsItems.lavashGratar'),
      description: t('menuCardsItems.descLavashGratar'),
      group: 'bread',
      weight: 150,
      price: 57,
    },
    {
      title: t('menuCardsItems.paineAlba'),
      description: t('menuCardsItems.descPaineAlba'),
      group: 'bread',
      weight: 150,
      price: 18,
    },
    {
      title: t('menuCardsItems.paineSecara'),
      description: t('menuCardsItems.descPaineSecara'),
      group: 'bread',
      weight: 75,
      price: 12,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/7c9233274de440128618687823a4ebfd/c7f200b789adb5498590b45651392bb2.webp',
      title: t('menuCardsItems.paineCasa'),
      description: t('menuCardsItems.descPaineCasa'),
      group: 'bread',
      weight: 150,
      price: 18,
    },
    {
      title: t('menuCardsItems.desertSef'),
      description: t('menuCardsItems.descDesertSef'),
      group: 'dessert',
      weight: 400,
      price: 171,
    },
    {
      title: t('menuCardsItems.desertCiorbagiica'),
      description: t('menuCardsItems.descDesertCiorbagiica'),
      group: 'dessert',
      weight: 300,
      price: 153,
    },
    {
      title: t('menuCardsItems.gevrek'),
      description: t('menuCardsItems.descGevrek'),
      group: 'dessert',
      weight: 150,
      price: 143,
    },
    {
      title: t('menuCardsItems.inghetataPlombir'),
      description: t('menuCardsItems.descInghetataPlombir'),
      group: 'dessert',
      weight: 150,
      price: 77,
    },
    {
      title: t('menuCardsItems.inghetataDulceata'),
      description: t('menuCardsItems.descInghetataDulceata'),
      group: 'dessert',
      weight: 200,
      price: 101,
    },
    {
      title: t('menuCardsItems.fructeSezon'),
      description: t('menuCardsItems.descFructeSezon'),
      group: 'dessert',
      weight: 100,
      price: 30,
    },
    {
      title: t('menuCardsItems.prajituraCeai'),
      description: t('menuCardsItems.descPrajituraCeai'),
      group: 'dessert',
      weight: 0,
      price: 13,
    },
    {
      title: t('menuCardsItems.prajituraAsorti'),
      description: t('menuCardsItems.descPrajituraAsorti'),
      group: 'dessert',
      weight: 0,
      price: 45,
    },
    {
      title: t('menuCardsItems.dulceataAsorti'),
      description: t('menuCardsItems.descDulceataAsorti'),
      group: 'dessert',
      weight: 50,
      price: 45,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/95e781a63c6a462380b0200adb9975e9/516934c8bd54b0040da344ebb02d751d.webp',
      title: t('menuCardsItems.vinAlbLitru'),
      description: t('menuCardsItems.descVinAlbLitru'),
      group: 'beverages',
      weight: 1000,
      price: 175,
    },
    {
      image:
        'https://straus.s3.amazonaws.com/media/CACHE_IMG/products2/df37f54221b94332b0b71be480e3fa7b/8b72f11ba7ef2bb77757f89d8e43748e.webp',
      title: t('menuCardsItems.vinRosuLitru'),
      description: t('menuCardsItems.descVinRosuLitru'),
      group: 'beverages',
      weight: 1000,
      price: 175,
    },
  ]
}

export default useGetMenuCardsItems
